services:
  - type: web
    name: al-insaf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
