services:
  - type: web
    name: al-insaf-ngo
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python create_db.py || (echo "Build failed" && exit 1)
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
